"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { CssBaseline } from "@nextui-org/react";
import { NextUIProvider, createTheme } from "@nextui-org/react";

const inter = Inter({ subsets: ['latin'] })
const darkTheme = createTheme({ type: "dark" });

/*export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>{CssBaseline.flush()}</head>
      <body className={inter.className}>
        <NextUIProvider theme={darkTheme}>
          {children}
        </NextUIProvider>
      </body>
    </html>
  )
}
