"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { CssBaseline } from "@nextui-org/react";
import { NextUIProvider, createTheme } from "@nextui-org/react";
import { ThemeProvider as NextThemesProvider } from 'next-themes';

const inter = Inter({ subsets: ['latin'] })

const lightTheme = createTheme({
  type: 'light',
  /*theme: {
    colors: {...}, // optional
  }*/
})

const darkTheme = createTheme({
  type: 'dark',
  /*theme: {
    colors: {...}, // optional
  }*/
})

/*export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>{CssBaseline.flush()}</head>
      <body className={inter.className}>
      <NextThemesProvider
          defaultTheme="system"
          attribute="class"
          value={{
            light: lightTheme.className,
            dark: darkTheme.className
          }}
        >
        <NextUIProvider>
          {children}
        </NextUIProvider>
      </NextThemesProvider>
      </body>
    </html>
  )
}
